class RouteNames{
  static const ROUTE_SPLASH_SCREEN= "ROUTE_SPLASH_SCREEN";
  static const ROUTE_LOGIN_SCREEN= "ROUTE_LOGIN_SCREEN";
  static const ROUTE_SIGNUP_SCREEN= "ROUTE_SIGNUP_SCREEN";
  static const ROUTE_HOME_SCREEN= "ROUTE_HOME_SCREEN";
  static const ROUTE_ABOUT_US_SCREEN= "ROUTE_ABOUT_US_SCREEN";
  static const ROUTE_CONTACT_US_SCREEN= "ROUTE_CONTACT_US_SCREEN";
  static const ROUTE_GET_STARTED_SCREEN= "ROUTE_GET_STARTED_SCREEN";
  static const ROUTE_RESULTS_SCREEN= "ROUTE_RESULTS_SCREEN";
  static const ROUTE_CHOOSE_BACKUP_SCREEN= "ROUTE_CHOOSE_BACKUP_SCREEN";
  static const ROUTE_CALCULATE_SYSTEM_SCREEN= "ROUTE_CALCULATE_SYSTEM_SCREEN";
  static const ROUTE_VENDORS_SCREEN= "ROUTE_VENDORS_SCREEN";
}